name: "jobs"
services:
  frontend:
    build:
      dockerfile: infra/dev.Dockerfile
      context: ../
    working_dir: /app/frontend
    volumes:
      - ../:/app/
    ports:
      - '3001:3001'
    environment:
      - VITE_PORT=3001
      - VITE_API_ENDPOINT=http://localhost:8081/api
      - DOCKER=true
    depends_on:
      - backend
    profiles: [ 'app' ]
    command: pnpm run dev
  backend:
    build:
      dockerfile: infra/dev.Dockerfile
      context: ../
    working_dir: /app/backend
    volumes:
      - ../:/app/
      - sqlite_data:/backend/src/db/mydb.sqlite
    ports:
      - '8081:8081'
    profiles: [ 'app' ]
    command: pnpm run dev:docker

volumes:
  sqlite_data:
    name: sqlite_db